name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Ensure Python version is >=3.10

      # Step 3: Clear pip cache (optional but recommended)
      - name: Clear pip cache
        run: |
          rm -rf ~/.cache/pip

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Wait for MySQL to be ready
              run: |
                for i in {1..30}; do
                  if mysqladmin ping -h127.0.0.1 -uroot -proot --silent; then
                    echo "MySQL is ready"
                    break
                  fi
                  echo "Waiting for MySQL to start..."
                  sleep 2
                done

      - name: Set environment variables
        run: |
          echo "MYSQL_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "MYSQL_PORT=3306" >> $GITHUB_ENV
          echo "MYSQL_DATABASE=test_db" >> $GITHUB_ENV
          echo "MYSQL_USER=test_user" >> $GITHUB_ENV
          echo "MYSQL_PASSWORD=test_password" >> $GITHUB_ENV

          
      # Step 5: Run migrations
      - name: Run migrations
        env:
          DJANGO_SETTINGS_MODULE: sareehmicro.settings  # Ensure your settings module is defined
        run: |
          python manage.py migrate

      # Step 6: Run tests
      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: sareehmicro.settings
        run: |
          python manage.py test

      # Step 7: Optional - Check for Django versions available (Debugging)
      - name: Check available Django versions
        run: |
          python -m pip index versions Django
