name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Ensure Python version is >=3.10

      # Step 3: Clear pip cache (optional but recommended)
      - name: Clear pip cache
        run: |
          rm -rf ~/.cache/pip

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run migrations
      - name: Run migrations
        env:
          DJANGO_SETTINGS_MODULE: sareehmicro.settings  # Ensure your settings module is defined
        run: |
          python manage.py migrate

      # Step 6: Run tests
      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: sareehmicro.settings
        run: |
          python manage.py test

      # Step 7: Optional - Check for Django versions available (Debugging)
      - name: Check available Django versions
        run: |
          python -m pip index versions Django
